"""add outbox pending index

Revision ID: 56d963dbba32
Revises: 0c299ec92d7b
Create Date: 2026-10-06 15:05:45.147564

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "56d963dbba32"
down_revision: str | Sequence[str] | None = "0c299ec92d7b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_outbox_pending",
        "outbox",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_outbox_pending", table_name="outbox", postgresql_where=sa.text("status = 'pending'")
    )
    # ### end Alembic commands ###
